/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMULARIO.VISTA;

import BASEDATO.EvenConexion;
import BASEDATO.LOCAL.ConnPostgres;
import BASEDATO.LOCAL.VariablesBD;
import Config_JSON.json_config;
import Evento.Color.cla_color_pelete;
import Evento.Fecha.EvenFecha;
import Evento.Jframe.EvenJFRAME;
import Evento.Mensaje.EvenMensajeJoptionpane;
import FORMULARIO.BO.BO_item_consumo_medidor;
import FORMULARIO.BO.BO_lectura_temp;
import FORMULARIO.DAO.DAO_item_consumo_medidor;
import FORMULARIO.DAO.DAO_lectura_temp;
import FORMULARIO.ENTIDAD.item_consumo_medidor;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.Timer;
import javax.swing.JOptionPane;

/**
 *
 * @author Digno
 */
public class FrmMenuMedidor extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuSainterLab
     */
    Connection conn = null;
    ConnPostgres conPs = new ConnPostgres();
    VariablesBD var = new VariablesBD();
    EvenJFRAME evetbl = new EvenJFRAME();
    EvenFecha evefec = new EvenFecha();
    EvenConexion eveconn = new EvenConexion();
    cla_color_pelete clacolor = new cla_color_pelete();
    json_config config = new json_config();
    EvenMensajeJoptionpane evemen = new EvenMensajeJoptionpane();
    item_consumo_medidor entcm = new item_consumo_medidor();
    DAO_item_consumo_medidor DAOcm = new DAO_item_consumo_medidor();
    BO_item_consumo_medidor BOcm = new BO_item_consumo_medidor();
    private DAO_lectura_temp ltmp_dao = new DAO_lectura_temp();
    BO_lectura_temp BOlt = new BO_lectura_temp();
    private Timer tiempo;

    void abrir_formulario() {
        conPs.ConnectDBpostgres(conn, false, false);
        conn = conPs.getConnPosgres();
        config.cargar_jsom_configuracion();
        titulo_sistema();
        this.setExtendedState(MAXIMIZED_BOTH);

    }

    void titulo_sistema() {
        String titulo = " BD: " + var.getPsLocalhost() + "/" + var.getPsPort() + "/" + var.getPsNomBD()
                + "/ Nombre:" + config.getNombre_sistema() + "/ Version:" + config.getVersion();
        this.setTitle(titulo);

    }

    void consulta_dato_medidor() {
        String titulo = "consulta_dato_medidor";
        String sql = "select dm.iddato_medidor, dm.numero_medidor,lt.idlectura_temp,lt.fecha_creado,lt.lectura_kw \n"
                + "from dato_medidor dm,lectura_temp lt\n"
                + "where dm.numero_medidor=lt.numero_medidor \n"
                + "order by lt.idlectura_temp asc;";
        int cant_insertado = 0;
        try {
            ResultSet rs = eveconn.getResulsetSQL(conn, sql, titulo);
            while (rs.next()) {
                cant_insertado++;
                int iddato_medidor = rs.getInt("iddato_medidor");
                String fecha_creado = rs.getString("fecha_creado");
                int lectura_kw = rs.getInt("lectura_kw");
                entcm.setC2fecha_creado(fecha_creado);
                entcm.setC3lectura_kw(lectura_kw);
                entcm.setC4fk_iddato_medidor(iddato_medidor);
                BOcm.insertar_item_consumo_medidor(entcm);
            }

        } catch (Exception e) {
            evemen.mensaje_error(e, sql, titulo);
        }
        JOptionPane.showMessageDialog(null, "CANTIDAD DE DATOS INSETADO EN LA TABLA ITEM_CONSUMO_MEDIDOR\nCANTIDAD: " + cant_insertado);

    }

    void boton_cargar_item_consumo_medidor() {
        if (evemen.MensajeGeneral_warning("ESTAS SEGURO DE EJECUTAR ESTE PROCESO DE INSERTAR AUTOMATICAMENTE LOS DATOS TEMPORALES DEL MEDIDOR", "DATOS TEMPORALES", "ACEPTAR", "CANCELAR")) {
            consulta_dato_medidor();
            BOlt.truncate_lectura_temp();
        }
    }

    public FrmMenuMedidor() {
        initComponents();
        abrir_formulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        btnfactura = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFactura = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuCliente = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuConfiguracion = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuMedidor = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnfactura.setText("FACTURA");
        btnfactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfacturaActionPerformed(evt);
            }
        });

        escritorio.setLayer(btnfactura, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnfactura)
                .addContainerGap(817, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnfactura)
                .addContainerGap(468, Short.MAX_VALUE))
        );

        jMenuFactura.setText("FACTURA");

        jMenuItem1.setText("NUEVA FACTURA");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuFactura.add(jMenuItem1);

        jMenuBar1.add(jMenuFactura);

        jMenuCliente.setText("CLIENTE");

        jMenuItem2.setText("CLIENTE");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuItem2);

        jMenuBar1.add(jMenuCliente);

        jMenuConfiguracion.setText("CONFIGURACION");

        jMenuItem3.setText("USUARIO");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuConfiguracion.add(jMenuItem3);

        jMenuItem6.setText("EMPRESA");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenuConfiguracion.add(jMenuItem6);

        jMenuItem7.setText("SIMULADOR");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenuConfiguracion.add(jMenuItem7);

        jMenuItem8.setText("CARGAR DATOS TEMPORAL");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenuConfiguracion.add(jMenuItem8);

        jMenuBar1.add(jMenuConfiguracion);

        jMenuMedidor.setText("MEDIDOR");

        jMenuItem4.setText("DATO MEDIDOR");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuMedidor.add(jMenuItem4);

        jMenuItem5.setText("TARIFA");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenuMedidor.add(jMenuItem5);

        jMenuBar1.add(jMenuMedidor);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmTarifa());
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmDatoMedidor());
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmCliente());
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmEmpresa());
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmFacturar());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnfacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfacturaActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmFacturar());
    }//GEN-LAST:event_btnfacturaActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmSimular());
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        boton_cargar_item_consumo_medidor();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmUsuario());
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        JDiaLogin log = new JDiaLogin(this, true);
        log.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuMedidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuMedidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuMedidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuMedidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuMedidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnfactura;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JMenu jMenuCliente;
    public static javax.swing.JMenu jMenuConfiguracion;
    public static javax.swing.JMenu jMenuFactura;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    public static javax.swing.JMenu jMenuMedidor;
    // End of variables declaration//GEN-END:variables
}
